static_ip:  192.168.86.97
vmid: 210
github_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61306336333333646639623031666234346630383762613932346663613234373263323937373566
  3834336632623261633561653438343430393830313965310a623664646363363764386132323334
  64623030333233396537316230656363316633653437313866613462346663333034356134373537
  6439346465653130320a326463666463303964663237353766633662396135383438396266633431
  62643261656439356637636334373230376235613432313465643233633932646239323535653762
  3334613837643131656632613935343961646632646235373734